# Generated by Django 5.2.8 on 2025-11-10 04:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenserecord',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='category_records', to='budget.expensecategory'),
        ),
        migrations.AlterField(
            model_name='expenserecord',
            name='subcategory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subcategory_records', to='budget.expensesubcategory'),
        ),
        migrations.AlterField(
            model_name='incomerecord',
            name='source',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='income_records', to='budget.incomesource'),
        ),
    ]
