# Generated by Django 5.2.8 on 2025-11-10 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0002_alter_expenserecord_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenserecord',
            name='description',
            field=models.TextField(blank=True, max_length=100),
        ),
    ]
