# Generated by Django 5.2.8 on 2025-11-17 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0003_alter_expenserecord_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='expenserecord',
            name='currency',
            field=models.CharField(default='eur', max_length=3),
        ),
    ]
