# Generated by Django 5.2.8 on 2025-11-18 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0005_alter_expenserecord_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incomerecord',
            name='currency',
            field=models.CharField(blank=True, default='eur', max_length=3),
        ),
    ]
