# Generated by Django 5.2.8 on 2025-11-18 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0006_alter_incomerecord_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incomerecord',
            name='description',
            field=models.TextField(blank=True, max_length=100),
        ),
    ]
