# Generated by Django 5.2.8 on 2025-12-01 18:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0007_alter_incomerecord_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='expensecategory',
            options={'verbose_name_plural': 'Expense Categories'},
        ),
        migrations.AlterModelOptions(
            name='expenserecord',
            options={'verbose_name_plural': 'Expense Records'},
        ),
        migrations.AlterModelOptions(
            name='expensesubcategory',
            options={'verbose_name_plural': 'Expense Subcategories'},
        ),
        migrations.AlterModelOptions(
            name='incomerecord',
            options={'verbose_name_plural': 'Income Records'},
        ),
        migrations.AlterModelOptions(
            name='incomesource',
            options={'verbose_name_plural': 'Income Sources'},
        ),
        migrations.AddField(
            model_name='expensesubcategory',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subcategories', to='budget.expensecategory'),
        ),
    ]
