# Generated by Django 5.2.8 on 2025-12-02 14:40

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0008_alter_expensecategory_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('target_value', models.DecimalField(decimal_places=2, max_digits=7)),
                ('currency', models.CharField(blank=True, default='eur', max_length=3)),
                ('created', models.DateTimeField(default=datetime.datetime(2025, 12, 2, 15, 40, 23, 373386))),
                ('deadline', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('in_progress', 'In Progress'), ('completed', 'Completed')], default='in_progress', max_length=15)),
            ],
        ),
        migrations.AddField(
            model_name='expenserecord',
            name='goal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='budget.goal'),
        ),
        migrations.AddField(
            model_name='incomerecord',
            name='goal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incomes', to='budget.goal'),
        ),
    ]
