# Generated by Django 5.2.8 on 2025-12-02 14:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0009_goal_expenserecord_goal_incomerecord_goal'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='description',
            field=models.TextField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='goal',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2025, 12, 2, 15, 58, 2, 937877)),
        ),
    ]
