# Generated by Django 5.2.8 on 2025-12-23 17:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0010_goal_description_alter_goal_created'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='goal',
            options={'verbose_name_plural': 'Goals'},
        ),
        migrations.RemoveField(
            model_name='incomerecord',
            name='goal',
        ),
        migrations.AlterField(
            model_name='goal',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2025, 12, 23, 18, 41, 7, 658187)),
        ),
    ]
